# Generated by Django 5.1.6 on 2025-04-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.IntegerField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='content.band')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='bands', to='content.genre'),
        ),
    ]
