# Generated by Django 5.1.6 on 2025-05-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
