# Generated by Django 5.1.6 on 2025-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bands', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('track_count', models.IntegerField()),
                ('tracks', models.TextField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
    ]
