# Generated by Django 5.1.6 on 2025-03-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_bands_delete_album_delete_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('track_count', models.IntegerField()),
                ('tracks', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='bands',
            old_name='author',
            new_name='band',
        ),
        migrations.RemoveField(
            model_name='bands',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='bands',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bands',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bands',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bands',
            name='track_count',
        ),
        migrations.RemoveField(
            model_name='bands',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='bands',
            name='year',
        ),
    ]
