# Generated by Django 5.1.6 on 2025-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_band_members_band_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='founded',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
