# Generated by Django 5.1.6 on 2025-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_band_track_delete_bands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover',
            new_name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
