# Generated by Django 5.1.6 on 2025-04-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_album_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='band',
            name='formed_year',
        ),
        migrations.RemoveField(
            model_name='band',
            name='image_url',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='band_logos/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.TextField(),
        ),
    ]
