# Generated by Django 5.1.6 on 2025-04-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_album_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='logo',
            field=models.ImageField(null=True, upload_to='band_logos/'),
        ),
    ]
