# Generated by Django 5.1.6 on 2025-04-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_band_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='founded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
